### ISSUE TITLE
Migrate major build pieces out as separate packages and bring them back in as packages

### ISSUE THREAD

**Issue by aurooba** [bacoords/block-theme#125]
Let's make the initial release work just with tangent's specific project structure:
- applies to `src/` folder

Should provide the following scripts:
- build
- start
- lint

We need a config file, where you can define:
- where you want your breakpoints scss to be stored and/or if there are any other json-to-scss conversions wanted, and/or if you even want that, defaults to generating the `utils/breakpoints.scss` file
- what folder you want your styles to be outputted to, defaults to `css/`
- what folder you want your scripts to be outputted to, defaults to `js/`
- where your `theme-json` folder lives, and/or if you even want the theme-json generator active, defaults to `src/theme-json/index.jsonc`

Eventually we should support/test HMR, but it's not needed for this beta release.

## Open Questions

- What should the build package be called?
- Should the json-to-scss and json-tree-to-json-file generators be pulled out as individual loaders?

## Tasks

- [x] Create `json-to-scss` webpack loader standalone
- [x] Create `json-dir-to-object` webpack loader standalone
- [ ] Create `tangent-scripts` build package standalone
