### ISSUE TITLE
Tracking Issue: Header.php Overhaul

### ISSUE THREAD

**Issue by bacoords** [bacoords/block-theme#21]
Things to think about (list still in progress)

- [x] How do we handle the site icon if we're trying to move away from Customizer?
- [ ] #14 Responsive Navigation should support Offcanvas by default
- [x] We probably need a JS build process FIRST to handle the JS above.
- [x] Can we use flex and column classes from core wordpress instead of writing custom?
