### ISSUE TITLE
Potential Utilities (tracking issue)

### ISSUE THREAD

**Issue by bacoords** [bacoords/block-theme#262]
I have a few utilities I've been thinking about bundling into this theme, but not sure if it's a good idea or not... open for discussion and ideas.

- [ ] Responsive flex order options (for columns or direct children of group blocks) - ability to say "on mobile, make this column first, second, etc"
- [ ] Responsive flex-wrap option for row block
- [ ] Block pattern-specific workflow tools, similar to bacoords/block-pattern-plugin
